
default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_POSTGRESQL_USERNAME'] %>
  password: <%= ENV['DB_POSTGRESQL_PASSWORD'] %>
  host:     <%= ENV['DB_POSTGRESQL_HOST'] %>
  port:     <%= ENV['DB_POSTGRESQL_PORT'] %>

development:
  <<: *default
  database: livraria-api_development

test:
  <<: *default
  database: livraria-api_test

production:
  <<: *default
  database: livraria-api_production
  username: livraria-api
  password: <%= ENV['LIVRARIA-API_DATABASE_PASSWORD'] %>
